export const COUNTRIES = [
    "United States",
    "Afghanistan",
    "Albania",
    "Algeria",
    "Andorra",
    "Angola",
    "Antigua and Barbuda",
    "Argentina",
    "Armenia",
    "Australia",
    "Austria",
    "Azerbaijan",
    "Bahamas",
    "Bahrain",
    "Bangladesh",
    "Barbados",
    "Belarus",
    "Belgium",
    "Belize",
    "Benin",
    "Bhutan",
    "Bolivia",
    "Bosnia and Herzegovina",
    "Botswana",
    "Brazil",
    "Brunei",
    "Bulgaria",
    "Burkina Faso",
    "Burundi",
    "Cabo Verde",
    "Cambodia",
    "Cameroon",
    "Canada",
    "Central African Republic",
    "Chad",
    "Chile",
    "China",
    "Colombia",
    "Comoros",
    "Congo (Congo-Brazzaville)",
    "Costa Rica",
    "Croatia",
    "Cuba",
    "Cyprus",
    "Czechia (Czech Republic)",
    "Democratic Republic of the Congo",
    "Denmark",
    "Djibouti",
    "Dominica",
    "Dominican Republic",
    "Ecuador",
    "Egypt",
    "El Salvador",
    "Equatorial Guinea",
    "Eritrea",
    "Estonia",
    "Eswatini",
    "Ethiopia",
    "Fiji",
    "Finland",
    "France",
    "Gabon",
    "Gambia",
    "Georgia",
    "Germany",
    "Ghana",
    "Greece",
    "Grenada",
    "Guatemala",
    "Guinea",
    "Guinea-Bissau",
    "Guyana",
    "Haiti",
    "Holy See",
    "Honduras",
    "Hungary",
    "Iceland",
    "India",
    "Indonesia",
    "Iran",
    "Iraq",
    "Ireland",
    "Israel",
    "Italy",
    "Jamaica",
    "Japan",
    "Jordan",
    "Kazakhstan",
    "Kenya",
    "Kiribati",
    "Kuwait",
    "Kyrgyzstan",
    "Laos",
    "Latvia",
    "Lebanon",
    "Lesotho",
    "Liberia",
    "Libya",
    "Liechtenstein",
    "Lithuania",
    "Luxembourg",
    "Madagascar",
    "Malawi",
    "Malaysia",
    "Maldives",
    "Mali",
    "Malta",
    "Marshall Islands",
    "Mauritania",
    "Mauritius",
    "Mexico",
    "Micronesia",
    "Moldova",
    "Monaco",
    "Mongolia",
    "Montenegro",
    "Morocco",
    "Mozambique",
    "Myanmar (formerly Burma)",
    "Namibia",
    "Nauru",
    "Nepal",
    "Netherlands",
    "New Zealand",
    "Nicaragua",
    "Niger",
    "Nigeria",
    "North Korea",
    "North Macedonia",
    "Norway",
    "Oman",
    "Pakistan",
    "Palau",
    "Palestine State",
    "Panama",
    "Papua New Guinea",
    "Paraguay",
    "Peru",
    "Philippines",
    "Poland",
    "Portugal",
    "Qatar",
    "Romania",
    "Russia",
    "Rwanda",
    "Saint Kitts and Nevis",
    "Saint Lucia",
    "Saint Vincent and the Grenadines",
    "Samoa",
    "San Marino",
    "Sao Tome and Principe",
    "Saudi Arabia",
    "Senegal",
    "Serbia",
    "Seychelles",
    "Sierra Leone",
    "Singapore",
    "Slovakia",
    "Slovenia",
    "Solomon Islands",
    "Somalia",
    "South Africa",
    "South Korea",
    "South Sudan",
    "Spain",
    "Sri Lanka",
    "Sudan",
    "Suriname",
    "Sweden",
    "Switzerland",
    "Syria",
    "Tajikistan",
    "Tanzania",
    "Thailand",
    "Timor-Leste",
    "Togo",
    "Tonga",
    "Trinidad and Tobago",
    "Tunisia",
    "Turkey",
    "Turkmenistan",
    "Tuvalu",
    "Uganda",
    "Ukraine",
    "United Arab Emirates",
    "United Kingdom",
    "Uruguay",
    "Uzbekistan",
    "Vanuatu",
    "Venezuela",
    "Vietnam",
    "Yemen",
    "Zambia",
    "Zimbabwe"
];

// Ported from src/config.py
export const SECTOR_INDUSTRY_MAP: Record<string, string[]> = {
    "": [""],
    "Other": ["Other"],
    "Basic Materials": [
        "Agricultural Inputs",
        "Aluminum",
        "Building Materials",
        "Chemicals",
        "Coking Coal",
        "Copper",
        "Gold",
        "Lumber & Wood Production",
        "Other Industrial Metals & Mining",
        "Other Precious Metals & Mining",
        "Paper & Paper Products",
        "Silver",
        "Specialty Chemicals",
        "Steel",
        "Thematic",
    ],
    "Communication Services": [
        "Advertising Agencies",
        "Broadcasting",
        "Communication Equipment",
        "Electronic Gaming & Multimedia",
        "Entertainment",
        "Internet Content & Information",
        "Publishing",
        "Telecom Services",
        "Thematic",
    ],
    "Consumer Cyclical": [
        "Apparel Manufacturing",
        "Apparel Retail",
        "Auto & Truck Dealerships",
        "Auto Manufacturers",
        "Auto Parts",
        "Department Stores",
        "Footwear & Accessories",
        "Furnishings, Fixtures & Appliances",
        "Gambling",
        "Home Improvement Retail",
        "Internet Retail",
        "Leisure",
        "Lodging",
        "Luxury Goods",
        "Packaging & Containers",
        "Personal Services",
        "Recreational Vehicles",
        "Residential Construction",
        "Resorts & Casinos",
        "Restaurants",
        "Specialty Retail",
        "Textile Manufacturing",
        "Travel Services",
        "Thematic",
    ],
    "Consumer Defensive": [
        "Beverages - Brewers",
        "Beverages - Non-Alcoholic",
        "Beverages - Wineries & Distilleries",
        "Confectioners",
        "Discount Stores",
        "Education & Training Services",
        "Farm Products",
        "Food Distribution",
        "Grocery Stores",
        "Household & Personal Products",
        "Packaged Foods",
        "Pharmaceutical Retailers",
        "Tobacco",
        "Thematic",
    ],
    "Energy": [
        "Oil & Gas Drilling",
        "Oil & Gas E&P",
        "Oil & Gas Equipment & Services",
        "Oil & Gas Integrated",
        "Oil & Gas Midstream",
        "Oil & Gas Refining & Marketing",
        "Thermal Coal",
        "Uranium",
        "Thematic",
    ],
    "Exchange-Traded Fund": [
        "Broad Market - Emerging Markets",
        "Broad Market - International Developed",
        "Broad Market - US",
        "Commodity - Gold",
        "Commodity - Oil",
        "Commodity - Silver",
        "Dividend - Growth",
        "Dividend - High Yield",
        "Factor - Growth",
        "Factor - Low Volatility",
        "Factor - Momentum",
        "Factor - Quality",
        "Factor - Value",
        "Fixed Income - Corporate Bond",
        "Fixed Income - Government Bond (Long-Term)",
        "Fixed Income - Government Bond (Short-Term)",
        "Fixed Income - High-Yield Bond",
        "Fixed Income - Municipal Bond",
        "Sector - Communication Services",
        "Sector - Consumer Cyclical",
        "Sector - Consumer Defensive",
        "Sector - Energy",
        "Sector - Financials",
        "Sector - Healthcare",
        "Sector - Industrials",
        "Sector - Materials",
        "Sector - Real Estate",
        "Sector - Technology",
        "Sector - Utilities",
    ],
    "Financial Services": [
        "Asset Management",
        "Banks - Diversified",
        "Banks - Regional",
        "Capital Markets",
        "Credit Services",
        "Financial Conglomerates",
        "Financial Data & Stock Exchanges",
        "Insurance - Diversified",
        "Insurance - Life",
        "Insurance - Property & Casualty",
        "Insurance - Reinsurance",
        "Insurance Brokers",
        "Mortgage Finance",
        "Shell Companies",
        "Thematic",
    ],
    "Healthcare": [
        "Biotechnology",
        "Diagnostics & Research",
        "Drug Manufacturers - General",
        "Drug Manufacturers - Specialty & Generic",
        "Health Information Services",
        "Healthcare Plans",
        "Medical Care Facilities",
        "Medical Devices",
        "Medical Distribution",
        "Medical Instruments & Supplies",
        "Thematic",
    ],
    "Industrials": [
        "Aerospace & Defense",
        "Airlines",
        "Airport Services",
        "Building Products & Equipment",
        "Business Equipment & Supplies",
        "Conglomerates",
        "Construction & Engineering",
        "Consulting Services",
        "Electrical Equipment & Parts",
        "Farm & Heavy Construction Machinery",
        "Industrial Distribution",
        "Infrastructure Operations",
        "Integrated Freight & Logistics",
        "Marine Shipping",
        "Metal Fabrication",
        "Pollution & Treatment Controls",
        "Railroads",
        "Rental & Leasing Services",
        "Security & Protection Services",
        "Specialty Business Services",
        "Specialty Industrial Machinery",
        "Staffing & Employment Services",
        "Tools & Accessories",
        "Trucking",
        "Waste Management",
        "Thematic",
    ],
    "Real Estate": [
        "Real Estate - Development",
        "Real Estate - Diversified",
        "Real Estate Services",
        "REIT - Diversified",
        "REIT - Healthcare Facilities",
        "REIT - Hotel & Motel",
        "REIT - Industrial",
        "REIT - Mortgage",
        "REIT - Office",
        "REIT - Residential",
        "REIT - Retail",
        "REIT - Specialty",
        "Thematic",
    ],
    "Technology": [
        "Computer Hardware",
        "Consumer Electronics",
        "Electronic Components",
        "Electronics & Computer Distribution",
        "Information Technology Services",
        "Scientific & Technical Instruments",
        "Semiconductor Equipment & Materials",
        "Semiconductors",
        "Software - Application",
        "Software - Infrastructure",
        "Solar",
        "Thematic",
    ],
    "Utilities": [
        "Utilities - Diversified",
        "Utilities - Independent Power Producers",
        "Utilities - Regulated Electric",
        "Utilities - Regulated Gas",
        "Utilities - Regulated Water",
        "Utilities - Renewable",
        "Thematic",
    ],
};

// Flattened list of all industries
export const ALL_INDUSTRIES = Array.from(new Set(
    Object.values(SECTOR_INDUSTRY_MAP).flat().filter(i => i)
)).sort();
