# -*- coding: utf-8 -*-
"""
Qt-free presentation defaults shared by the GUI and the web/API backend.

This module deliberately has no GUI (PySide6) dependency so that server-side
code (e.g. config_manager) can import column definitions and graph date
defaults without pulling in Qt. GUI-only helpers and QColor constants live in
utils.py, which re-exports the names defined here for backwards compatibility.
"""
from datetime import date, timedelta

from config import DEFAULT_GRAPH_DAYS_AGO

# --- Graph Defaults ---
DEFAULT_GRAPH_START_DATE = date.today() - timedelta(days=DEFAULT_GRAPH_DAYS_AGO)
DEFAULT_GRAPH_END_DATE = date.today()  # Default end today


def get_column_definitions(display_currency="USD"):
    """Generates a mapping from UI table headers to DataFrame column names.

    This allows the UI header text to be independent of the underlying column names
    generated by the portfolio logic, especially handling currency-specific columns.

    Args:
        display_currency (str, optional): The currency code (e.g., "USD", "THB")
            to incorporate into currency-dependent column names. Defaults to "USD".

    Returns:
        Dict[str, str]: A dictionary where keys are user-friendly UI header names
            (e.g., 'Mkt Val') and values are the corresponding actual DataFrame
            column names expected from `portfolio_logic` (e.g., 'Market Value (USD)').
    """
    return {
        # UI Header Name : Actual DataFrame Column Name (potentially with currency)
        "Account": "Account",
        "Symbol": "Symbol",
        "Sector": "Sector",
        "Industry": "Industry",
        "Quantity": "Quantity",
        "Day Chg": f"Day Change ({display_currency})",
        "Day Chg %": "Day Change %",
        "Avg Cost": f"Avg Cost ({display_currency})",
        "Price": f"Price ({display_currency})",
        "Cost Basis": f"Cost Basis ({display_currency})",
        "Mkt Val": f"Market Value ({display_currency})",
        "% of Total": "pct_of_total",
        "Unreal. G/L": f"Unreal. Gain ({display_currency})",
        "Unreal. G/L %": "Unreal. Gain %",
        "Real. G/L": f"Realized Gain ({display_currency})",
        "Divs": f"Dividends ({display_currency})",
        "Fees": f"Commissions ({display_currency})",
        "Total G/L": f"Total Gain ({display_currency})",
        "Total Ret %": "Total Return %",  # Calculated using Cumulative Investment
        "IRR (%)": "IRR (%)",
        # Optional columns that might be added for debugging or other features:
        "Total Buy Cost": f"Total Buy Cost ({display_currency})",
        "Yield (Cost) %": "Div. Yield (Cost) %",
        "Yield (Mkt) %": "Div. Yield (Current) %",
        "FX G/L": f"FX Gain/Loss ({display_currency})",
        "FX G/L %": "FX Gain/Loss %",
        "Est. Income": f"Est. Ann. Income ({display_currency})",
        # 'Cumulative Investment': f'Cumulative Investment ({display_currency})',
        # 'Price Source': 'Price Source',
    }
