# Auto-generated from main_gui.py modularization
import os
import sys
from typing import Dict, Any, Optional
from datetime import date, timedelta
import config

from config import (
    DEBOUNCE_INTERVAL_MS,
    MANUAL_OVERRIDES_FILENAME,
    DEFAULT_API_KEY,
    CHART_MAX_SLICES,
    PIE_CHART_FIG_SIZE,
    PERF_CHART_FIG_SIZE,
    CHART_DPI,
    INDICES_FOR_HEADER,
    CSV_DATE_FORMAT,
    COMMON_CURRENCIES,
    DEFAULT_GRAPH_DAYS_AGO,  # Now defined before its use
    DEFAULT_GRAPH_INTERVAL,
    DEFAULT_GRAPH_BENCHMARKS,
    BENCHMARK_MAPPING,
    BENCHMARK_OPTIONS_DISPLAY,
    COLOR_BG_DARK,
    COLOR_BG_HEADER_LIGHT,
    COLOR_BG_HEADER_ORIGINAL,
    COLOR_TEXT_DARK,
    COLOR_TEXT_SECONDARY,
    COLOR_ACCENT_TEAL,
    COLOR_BORDER_LIGHT,
    COLOR_BORDER_DARK,
    COLOR_GAIN,
    COLOR_LOSS,
    DEFAULT_CSV,
)

from PySide6.QtGui import QColor
from config import COLOR_GAIN

QCOLOR_GAIN = QColor(COLOR_GAIN)


def resource_path(relative_path):
    """Get absolute path to resource, works for dev and for PyInstaller"""
    try:
        # PyInstaller creates a temp folder and stores path in _MEIPASS
        base_path = sys._MEIPASS
    except Exception:
        # For development, __file__ is the path to the current script.
        # os.path.dirname(__file__) gives the directory of the script.
        base_path = os.path.dirname(os.path.abspath(__file__))
    return os.path.join(base_path, relative_path)


# For DEFAULT_CSV, it's often better to let the user select it or store its path in config,
# rather than bundling a specific "my_transactions.csv".
# If "my_transactions.csv" is an example/template, then resource_path could be used.
# DEFAULT_CSV is now imported from config.py

# --- User-specific file paths using QStandardPaths ---
# APP_NAME_FOR_QT was "Investa". config.APP_NAME ("Investa") will be used instead.

# CONFIG_FILE and MANUAL_PRICE_FILE will be initialized as instance attributes
# in PortfolioApp.__init__ after QApplication is fully configured.

# DEFAULT_API_KEY is now imported from config.py

# --- Graph Defaults ---
# DEFAULT_GRAPH_START_DATE will use config.DEFAULT_GRAPH_DAYS_AGO
DEFAULT_GRAPH_START_DATE = date.today() - timedelta(days=DEFAULT_GRAPH_DAYS_AGO)
DEFAULT_GRAPH_END_DATE = date.today()  # Default end today
# DEFAULT_GRAPH_INTERVAL is imported from config.py
# DEFAULT_GRAPH_BENCHMARKS is imported from config.py
# BENCHMARK_MAPPING is imported from config.py
# BENCHMARK_OPTIONS_DISPLAY is imported from config.py

# --- Theme Colors ---
# Define color palette for styling the UI (Minimal Theme)
# Hex color strings (COLOR_BG_DARK, etc.) are now imported from config.py
# QColor objects will be defined using these imported hex strings.

# Convert hex colors to QColor objects for easier use in Qt palettes
# These are the base light theme colors. Themed versions will be created in __init__.
QCOLOR_GAIN = QColor(COLOR_GAIN)
QCOLOR_LOSS = QColor(COLOR_LOSS)
QCOLOR_TEXT_DARK = QColor(COLOR_TEXT_DARK)
QCOLOR_TEXT_SECONDARY = QColor(COLOR_TEXT_SECONDARY)
# Add other base QColor objects if they are directly used and need theming
QCOLOR_BG_DARK = QColor(
    COLOR_BG_DARK
)  # Used for QWidget background and figure backgrounds
QCOLOR_BG_HEADER_LIGHT = QColor(COLOR_BG_HEADER_LIGHT)  # Used for some headers/frames
QCOLOR_BORDER_LIGHT = QColor(COLOR_BORDER_LIGHT)  # General light borders
QCOLOR_BORDER_DARK = QColor(
    COLOR_BORDER_DARK
)  # General dark borders (like table header bottom)
QCOLOR_ACCENT_TEAL = QColor(COLOR_ACCENT_TEAL)  # Primary accent for lines/etc.


# --- Fallback QColor Constants (for dialogs if themed attributes are not on parent) ---
FALLBACK_QCOLOR_GAIN = QCOLOR_GAIN
FALLBACK_QCOLOR_LOSS = QCOLOR_LOSS
FALLBACK_QCOLOR_TEXT_DARK = QCOLOR_TEXT_DARK
FALLBACK_QCOLOR_TEXT_SECONDARY = QCOLOR_TEXT_SECONDARY
FALLBACK_QCOLOR_BG_DARK = QCOLOR_BG_DARK
FALLBACK_QCOLOR_BG_HEADER_LIGHT = QCOLOR_BG_HEADER_LIGHT
FALLBACK_QCOLOR_BORDER_LIGHT = QCOLOR_BORDER_LIGHT
FALLBACK_QCOLOR_BORDER_DARK = QCOLOR_BORDER_DARK
FALLBACK_QCOLOR_ACCENT_TEAL = QCOLOR_ACCENT_TEAL
# Add any other FALLBACK_QCOLOR_ needed by dialogs, mirroring the global QCOLOR_ definitions


# --- Column Definition Helper ---


def get_column_definitions(display_currency="USD"):
    """Generates a mapping from UI table headers to DataFrame column names.

    This allows the UI header text to be independent of the underlying column names
    generated by the portfolio logic, especially handling currency-specific columns.

    Args:
        display_currency (str, optional): The currency code (e.g., "USD", "THB")
            to incorporate into currency-dependent column names. Defaults to "USD".

    Returns:
        Dict[str, str]: A dictionary where keys are user-friendly UI header names
            (e.g., 'Mkt Val') and values are the corresponding actual DataFrame
            column names expected from `portfolio_logic` (e.g., 'Market Value (USD)').
    """
    return {
        # UI Header Name : Actual DataFrame Column Name (potentially with currency)
        "Account": "Account",
        "Symbol": "Symbol",
        "Sector": "Sector",
        "Industry": "Industry",
        "Quantity": "Quantity",
        f"Day Chg": f"Day Change ({display_currency})",
        "Day Chg %": "Day Change %",
        "Avg Cost": f"Avg Cost ({display_currency})",
        "Price": f"Price ({display_currency})",
        "Cost Basis": f"Cost Basis ({display_currency})",
        "Mkt Val": f"Market Value ({display_currency})",
        "% of Total": "pct_of_total",
        "Unreal. G/L": f"Unreal. Gain ({display_currency})",
        "Unreal. G/L %": "Unreal. Gain %",
        "Real. G/L": f"Realized Gain ({display_currency})",
        "Divs": f"Dividends ({display_currency})",
        "Fees": f"Commissions ({display_currency})",
        "Total G/L": f"Total Gain ({display_currency})",
        "Total Ret %": "Total Return %",  # Calculated using Cumulative Investment
        "IRR (%)": "IRR (%)",
        # Optional columns that might be added for debugging or other features:
        "Total Buy Cost": f"Total Buy Cost ({display_currency})",
        "Yield (Cost) %": f"Div. Yield (Cost) %",
        "Yield (Mkt) %": f"Div. Yield (Current) %",
        "FX G/L": f"FX Gain/Loss ({display_currency})",
        "FX G/L %": "FX Gain/Loss %",
        f"Est. Income": f"Est. Ann. Income ({display_currency})",
        # 'Cumulative Investment': f'Cumulative Investment ({display_currency})',
        # 'Price Source': 'Price Source',
    }


# --- Helper Classes for Background Processing ---

from PySide6.QtWidgets import QStyledItemDelegate, QStyle
from PySide6.QtGui import QColor


class GroupHeaderDelegate(QStyledItemDelegate):
    def __init__(self, parent=None, theme="light"):
        super().__init__(parent)
        self.theme = theme

    def paint(self, painter, option, index):
        super().paint(painter, option, index)
